spring:
  application:
    name: microservice-api-gateway
server:
  port: 8050
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10 #leaseExpirationDurationInSeconds，表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    lease-renewal-interval-in-seconds: 5 #leaseRenewalIntervalInSeconds，表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该
    hostname: gateway
  client:
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    serviceUrl:
      defaultZone: http://admin:admin@discovery:8761/eureka/
zuul:
  ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    movie:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /feign/**
      stripPrefix: false # 请求"/myusers/101"将被跳转到"users"服务的"/myusers/101"上.
      service-id:  microservice-consumer-movie-feign-with-hystrix-stream     # Eureka中的serviceId



# 路由配置方式一
#这个zuul 是spring cloud 智能路由配置，也可以配置反向代理 以下zuul.routes 固定
#service0 service1 是注册到eureka服务器中的服务名称 这段配置意思是如果访问
#http://localhost:8083/service/0/ 下的URL 都会被路由到服务接口service0下
#zuul:
  #routes:
    #microservice-consumer-movie-feign-with-hystrix-stream: /service/feign/**
    #service1: /service/1/**